# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NUnit.org
email: 
description: NUnit is the most popular unit test framework for .NET.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nunit.org" # the base hostname & protocol for your site
twitter_username: nunit
github_username:  nunit

# Build settings
markdown: kramdown
